[package]
name = "mutable-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full", "rt"] }
async-fs = "1.5.0"
futures-lite = "1.12.0"
futures = "0.3.19"
